import Head from "next/head";
import PostList from "~/components/PostList";
import { api } from "~/utils/api";

export default function Home() {
  const postResponse = api.post.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostList
        isLoading={postResponse.isLoading}
        isError={postResponse.isError}
        data={postResponse.data}
      />
    </>
  );
}
